### ISSUE TITLE
Error running ./configure

### ISSUE THREAD

**Issue by chanon** [tlwg/libthai#14]
Hello, trying to build libthai, but ./configure ends with this error:

```
./configure: line 12540: syntax error near unexpected token `$DOXYGEN_VER,ge,DOXYGEN_REQ_VER,'
./configure: line 12540: `    AX_COMPARE_VERSION($DOXYGEN_VER,ge,DOXYGEN_REQ_VER,'

```
I have tried setting the $DOXYGEN_VER environment variable, but it doesn't help.

**Comment by chanon** [comment]
Also / alternatively, could you point to where I could get a pre-built thbrk.tri file?

**Comment by chanon** [comment]
Nevermind, I just deleted those lines from the generated configure file.

**Comment by thep** [comment]
In fact, you just need to install `autoconf-archive` to get the macro definitions.
