### ISSUE TITLE
ขออนุญาตใช้งาน libthai กับซอฟต์แวร์ของ บริษัท โค้ดฮาร์ด จำกัด

### ISSUE THREAD

**Issue by rungwiroon** [tlwg/libthai#20]
ผมมาจากบริษัท โค้ดฮาร์ด จำกัด มีความสนใจที่จะนำเอา libthai
ไปใช้กับโปรเจ็คที่เป็น closed-source เพื่อการค้า แต่เนื่องจากสัญญาอนุญาตเป็น LGPL2.1 ทำให้ไม่สามารถใช้งานได้
จึงขอความอนุญาตจากทีมงาน TLWG เป็นกรณีพิเศษเพื่อให้นำไปใช้งานได้ครับ

ขอแสดงความนับถือ
รุ่งวิรุณ โกมลิทธิพงศ์
CTO
[CodeHard co., ltd](https://codehard.co.th/)

**Comment by bact** [comment]
ซอฟต์แวร์ที่เป็น GNU Lesser General Public License สามารถใช้กับซอฟต์แวร์ที่ไม่ใช่ GPL/LGPL ได้นะครับ

**Comment by rungwiroon** [comment]
เข้าใจล่ะครับ ขอบคุณมากครับ
